apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Chart.Name }}
  issuerRef:
    name: {{ .Values.certificate.issuer }}
    kind: ClusterIssuer
  commonName: {{ .Values.certificate.commonName }}
  dnsNames:
{{- range .Values.certificate.dnsNames }}
  - {{ . }}
{{- end }}